# Generated by Django 5.0.4 on 2024-04-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=100)),
                ('alumno', models.TextField()),
                ('asac', models.TextField(max_length=100)),
                ('carrera', models.TextField(max_length=100)),
            ],
        ),
    ]
