# Generated by Django 5.0.4 on 2024-04-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_estadias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='proyectos_estadias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tbl_addproyecto',
            },
        ),
        migrations.DeleteModel(
            name='Proyectos',
        ),
    ]
