# Generated by Django 5.0.4 on 2024-04-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_estadias', '0002_proyectos_estadias_delete_proyectos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proyectos_estadias',
            table='tbl_addproyectos',
        ),
    ]
