# Generated by Django 5.0.4 on 2024-04-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_estadias', '0003_alter_proyectos_estadias_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='proyectos_estadias',
        ),
    ]
