# Generated by Django 5.0.4 on 2024-04-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos_estadias', '0004_delete_proyectos_estadias'),
    ]

    operations = [
        migrations.CreateModel(
            name='proyectos_estadias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tbl_addproyectos',
            },
        ),
    ]
