# Generated by Django 5.0.4 on 2024-04-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_estadias', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='proyectos_estadias',
        ),
    ]
