# Generated by Django 5.0.4 on 2024-04-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_estadias', '0007_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='proyectos',
            new_name='proyecto',
        ),
        migrations.AlterModelTable(
            name='proyecto',
            table='proyecto',
        ),
    ]
