# Generated by Django 5.0.4 on 2024-04-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_estadias', '0010_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registro',
            table='registro',
        ),
    ]
