# Generated by Django 5.0.4 on 2024-04-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_estadias', '0011_alter_registro_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registro',
        ),
    ]
