# Generated by Django 5.0.4 on 2024-04-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_estadias', '0013_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registro',
        ),
    ]
