# Generated by Django 5.0.4 on 2024-04-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_estadias', '0020_estadia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estadia',
        ),
    ]
