# Generated by Django 5.0.4 on 2024-04-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_estadias', '0023_delete_estadia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(blank=True, choices=[('ADC', 'ADC'), ('MET', 'MET'), ('QAI', 'QAI'), ('PIA', 'PIA'), ('QAM', 'QAM'), ('ERC', 'ERC'), ('IDGS', 'IDGS'), ('ITEA', 'ITEA'), ('IMET', 'IMET'), ('IER', 'IER'), ('ISIP', 'ISIP'), ('IPQ', 'IPQ'), ('LGCH', 'LGCH')], default='2', help_text='Prioridad de la tarea', max_length=20)),
            ],
            options={
                'verbose_name': 'Estadia',
                'verbose_name_plural': 'Estadias',
            },
        ),
    ]
