# Generated by Django 5.0.4 on 2024-04-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_estadias', '0031_delete_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadia',
            name='archivo',
            field=models.FileField(null=True, upload_to='documentos/%Y/%m/%d/'),
        ),
    ]
