# Generated by Django 5.0.4 on 2024-04-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_estadias', '0032_estadia_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadia',
            name='archivo',
            field=models.FileField(null=True, upload_to='documentos_pdf/%Y/%m/%d/'),
        ),
    ]
