# Generated by Django 5.0.4 on 2024-04-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_estadias', '0034_alter_estadia_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadia',
            old_name='asaca',
            new_name='asesor_academico',
        ),
        migrations.RenameField(
            model_name='estadia',
            old_name='asemp',
            new_name='asesor_empresarial',
        ),
    ]
